export type ToolCategory = {
  slug: string;
  name: string;
  description: string;
  icon: string;
};

export type Tool = {
  slug: string;
  name: string;
  shortDescription: string;
  categorySlug: string;
  icon: string;
  isFeatured?: boolean;
  isFree?: boolean;
  creditCost: number;
  clientSide: boolean;
};

export const CATEGORIES: ToolCategory[] = [
  { slug: "pdf", name: "PDF", description: "Compress, convert, merge, split and edit PDF files.", icon: "📄" },
  { slug: "image", name: "Image", description: "Resize, convert, compress and enhance images.", icon: "🖼️" },
  { slug: "video", name: "Video", description: "Trim, compress, convert video and extract audio — all in-browser.", icon: "🎬" },
  { slug: "converter", name: "Converters", description: "Convert between file formats: images, data, spreadsheets, markdown.", icon: "⇄" },
  { slug: "ai", name: "AI", description: "AI-powered writing, summarising and generation tools.", icon: "✨" },
  { slug: "developer", name: "Developer", description: "Everyday utilities for developers — formatters, encoders, testers.", icon: "🧑‍💻" },
];

export const TOOLS: Tool[] = [
  {
    slug: "json-formatter",
    name: "JSON Formatter",
    shortDescription: "Pretty print, minify and validate JSON in your browser.",
    categorySlug: "developer",
    icon: "{ }",
    isFeatured: true,
    isFree: true,
    creditCost: 0,
    clientSide: true,
  },
  {
    slug: "base64",
    name: "Base64 Encoder / Decoder",
    shortDescription: "Encode and decode Base64 text — locally, never uploaded.",
    categorySlug: "developer",
    icon: "B64",
    isFeatured: true,
    isFree: true,
    creditCost: 0,
    clientSide: true,
  },
  {
    slug: "url-encoder",
    name: "URL Encoder / Decoder",
    shortDescription: "Percent-encode or decode URL strings and query params.",
    categorySlug: "developer",
    icon: "%",
    isFree: true,
    creditCost: 0,
    clientSide: true,
  },
  {
    slug: "jwt-decoder",
    name: "JWT Decoder",
    shortDescription: "Inspect JWT header, payload and signature — client-side only.",
    categorySlug: "developer",
    icon: "🔐",
    isFeatured: true,
    isFree: true,
    creditCost: 0,
    clientSide: true,
  },
  {
    slug: "regex-tester",
    name: "Regex Tester",
    shortDescription: "Test regular expressions with live match highlighting.",
    categorySlug: "developer",
    icon: ".*",
    isFree: true,
    creditCost: 0,
    clientSide: true,
  },
  {
    slug: "password-generator",
    name: "Password Generator",
    shortDescription: "Generate strong, cryptographically random passwords.",
    categorySlug: "developer",
    icon: "🔑",
    isFeatured: true,
    isFree: true,
    creditCost: 0,
    clientSide: true,
  },
  {
    slug: "hash-generator",
    name: "Hash Generator",
    shortDescription: "MD5, SHA-1, SHA-256 and SHA-512 hashes for any text.",
    categorySlug: "developer",
    icon: "#",
    isFree: true,
    creditCost: 0,
    clientSide: true,
  },
  {
    slug: "color-converter",
    name: "Color Converter",
    shortDescription: "Convert between HEX, RGB, HSL and HSV with a live picker.",
    categorySlug: "developer",
    icon: "🎨",
    isFeatured: true,
    isFree: true,
    creditCost: 0,
    clientSide: true,
  },
  {
    slug: "image-resizer",
    name: "Image Resizer",
    shortDescription: "Resize images with presets or custom dimensions. Export PNG, JPG or WEBP.",
    categorySlug: "image",
    icon: "📐",
    isFeatured: true,
    isFree: true,
    creditCost: 0,
    clientSide: true,
  },
  {
    slug: "image-compressor",
    name: "Image Compressor",
    shortDescription: "Compress JPEG, PNG or WEBP images with a quality slider — right in your browser.",
    categorySlug: "image",
    icon: "🗜️",
    isFeatured: true,
    isFree: true,
    creditCost: 0,
    clientSide: true,
  },
  {
    slug: "image-to-pdf",
    name: "Image to PDF",
    shortDescription: "Combine multiple images into a single PDF document.",
    categorySlug: "image",
    icon: "🖼️",
    isFree: true,
    creditCost: 0,
    clientSide: true,
  },
  {
    slug: "image-crop",
    name: "Crop Image",
    shortDescription: "Drag to crop any image and export as PNG or JPG — 100% browser.",
    categorySlug: "image",
    icon: "✂️",
    isFree: true,
    creditCost: 0,
    clientSide: true,
  },
  {
    slug: "image-rotate-flip",
    name: "Rotate & Flip Image",
    shortDescription: "Rotate 90°, flip horizontally or vertically and export the result.",
    categorySlug: "image",
    icon: "🔄",
    isFree: true,
    creditCost: 0,
    clientSide: true,
  },
  {
    slug: "image-remove-exif",
    name: "Remove Image EXIF",
    shortDescription: "Strip EXIF, GPS and camera metadata from photos before sharing.",
    categorySlug: "image",
    icon: "🛡️",
    isFree: true,
    creditCost: 0,
    clientSide: true,
  },
  {
    slug: "image-to-base64",
    name: "Image to Base64",
    shortDescription: "Convert images to Base64 / data URL for CSS, HTML or JSON embedding.",
    categorySlug: "image",
    icon: "🔤",
    isFree: true,
    creditCost: 0,
    clientSide: true,
  },
  {
    slug: "pdf-rotate",
    name: "Rotate PDF",
    shortDescription: "Rotate selected pages by 90°, 180° or 270° — client-side.",
    categorySlug: "pdf",
    icon: "🔁",
    isFree: true,
    creditCost: 0,
    clientSide: true,
  },
  {
    slug: "pdf-delete-pages",
    name: "Delete PDF Pages",
    shortDescription: "Remove specific pages from a PDF and download the trimmed file.",
    categorySlug: "pdf",
    icon: "🗑️",
    isFree: true,
    creditCost: 0,
    clientSide: true,
  },
  {
    slug: "pdf-to-images",
    name: "PDF to Images",
    shortDescription: "Render every PDF page as a PNG or JPG image at 1x–3x resolution.",
    categorySlug: "pdf",
    icon: "🖼️",
    isFree: true,
    creditCost: 0,
    clientSide: true,
  },
  {
    slug: "pdf-ocr",
    name: "PDF OCR",
    shortDescription: "Extract text from scanned PDFs in 7 languages — 100% in your browser.",
    categorySlug: "pdf",
    icon: "🔍",
    isFree: true,
    creditCost: 0,
    clientSide: true,
  },
  {
    slug: "text-to-speech",
    name: "Text to Speech",
    shortDescription: "Convert text to natural speech with voice and speed control.",
    categorySlug: "ai",
    icon: "🔊",
    isFeatured: true,
    isFree: true,
    creditCost: 0,
    clientSide: true,
  },
  {
    slug: "word-counter",
    name: "Word Counter",
    shortDescription: "Live word, character, sentence, paragraph and reading-time counts.",
    categorySlug: "developer",
    icon: "🔢",
    isFree: true,
    creditCost: 0,
    clientSide: true,
  },
  {
    slug: "case-converter",
    name: "Case Converter",
    shortDescription: "Convert text between UPPER, lower, Title, camelCase, snake_case, kebab-case and PascalCase.",
    categorySlug: "developer",
    icon: "Aa",
    isFree: true,
    creditCost: 0,
    clientSide: true,
  },
  {
    slug: "lorem-ipsum",
    name: "Lorem Ipsum Generator",
    shortDescription: "Generate placeholder paragraphs, sentences or words instantly.",
    categorySlug: "developer",
    icon: "¶",
    isFree: true,
    creditCost: 0,
    clientSide: true,
  },
  {
    slug: "pdf-merge",
    name: "PDF Merge",
    shortDescription: "Combine multiple PDFs into a single document — right in your browser.",
    categorySlug: "pdf",
    icon: "📎",
    isFeatured: true,
    isFree: true,
    creditCost: 0,
    clientSide: true,
  },
  {
    slug: "pdf-split",
    name: "PDF Split",
    shortDescription: "Extract specific pages or page ranges from a PDF.",
    categorySlug: "pdf",
    icon: "✂️",
    isFree: true,
    creditCost: 0,
    clientSide: true,
  },
  {
    slug: "pdf-compressor",
    name: "PDF Compressor",
    shortDescription: "Re-save a PDF with object streams to reduce its file size.",
    categorySlug: "pdf",
    icon: "🗜️",
    isFree: true,
    creditCost: 0,
    clientSide: true,
  },
  {
    slug: "pdf-to-word",
    name: "PDF to Word",
    shortDescription: "Extract PDF text into an editable .docx (best-effort formatting).",
    categorySlug: "pdf",
    icon: "📝",
    isFree: true,
    creditCost: 0,
    clientSide: true,
  },
  {
    slug: "ocr",
    name: "OCR — Image to Text",
    shortDescription: "Extract text from images using in-browser Tesseract OCR.",
    categorySlug: "image",
    icon: "🔍",
    isFeatured: true,
    isFree: true,
    creditCost: 0,
    clientSide: true,
  },
  {
    slug: "remove-background",
    name: "Remove Image Background",
    shortDescription: "Erase image backgrounds automatically — runs entirely in your browser.",
    categorySlug: "image",
    icon: "🪄",
    isFeatured: true,
    isFree: true,
    creditCost: 0,
    clientSide: true,
  },
  {
    slug: "summarize",
    name: "AI Text Summarizer",
    shortDescription: "Summarise long text with adjustable length and style.",
    categorySlug: "ai",
    icon: "📃",
    isFeatured: true,
    isFree: true,
    creditCost: 1,
    clientSide: false,
  },
  {
    slug: "translate",
    name: "AI Text Translator",
    shortDescription: "Translate text between English, Vietnamese, Spanish and Indonesian.",
    categorySlug: "ai",
    icon: "🌐",
    isFeatured: true,
    isFree: true,
    creditCost: 1,
    clientSide: false,
  },
  {
    slug: "rewrite",
    name: "AI Rewriter",
    shortDescription: "Paraphrase and rewrite text in a formal, casual or professional tone.",
    categorySlug: "ai",
    icon: "✍️",
    isFree: true,
    creditCost: 1,
    clientSide: false,
  },
  {
    slug: "chat-pdf",
    name: "Chat with PDF",
    shortDescription: "Upload a PDF and ask questions about its content — powered by AI.",
    categorySlug: "ai",
    icon: "💬",
    isFeatured: true,
    isFree: true,
    creditCost: 2,
    clientSide: false,
  },
  {
    slug: "csv-to-json",
    name: "CSV to JSON Converter",
    shortDescription: "Convert CSV data into a clean JSON array — paste or upload.",
    categorySlug: "developer",
    icon: "⇄",
    isFree: true,
    creditCost: 0,
    clientSide: true,
  },
  {
    slug: "json-to-csv",
    name: "JSON to CSV Converter",
    shortDescription: "Turn a JSON array into a downloadable CSV file.",
    categorySlug: "developer",
    icon: "⇄",
    isFree: true,
    creditCost: 0,
    clientSide: true,
  },
  {
    slug: "uuid-generator",
    name: "UUID Generator",
    shortDescription: "Generate batches of UUID v4 or v5 identifiers.",
    categorySlug: "developer",
    icon: "🆔",
    isFree: true,
    creditCost: 0,
    clientSide: true,
  },
  {
    slug: "html-entities",
    name: "HTML Entity Encoder / Decoder",
    shortDescription: "Encode or decode HTML entities like &amp;, &lt;, &gt; and more.",
    categorySlug: "developer",
    icon: "&",
    isFree: true,
    creditCost: 0,
    clientSide: true,
  },
  {
    slug: "timestamp-converter",
    name: "Unix Timestamp Converter",
    shortDescription: "Convert between Unix timestamps (seconds/ms) and human dates.",
    categorySlug: "developer",
    icon: "⏱",
    isFree: true,
    creditCost: 0,
    clientSide: true,
  },
  // ── Video ──
  {
    slug: "video-to-gif",
    name: "Video to GIF",
    shortDescription: "Convert a video clip into an animated GIF — trim range, fps and width.",
    categorySlug: "video",
    icon: "🎞️",
    isFeatured: true,
    isFree: true,
    creditCost: 0,
    clientSide: true,
  },
  {
    slug: "video-trimmer",
    name: "Video Trimmer",
    shortDescription: "Cut a section of any video without re-encoding — fast and lossless.",
    categorySlug: "video",
    icon: "✂️",
    isFree: true,
    creditCost: 0,
    clientSide: true,
  },
  {
    slug: "video-compressor",
    name: "Video Compressor",
    shortDescription: "Compress MP4/WebM video with quality control — right in your browser.",
    categorySlug: "video",
    icon: "🗜️",
    isFeatured: true,
    isFree: true,
    creditCost: 0,
    clientSide: true,
  },
  {
    slug: "audio-extractor",
    name: "Audio Extractor",
    shortDescription: "Extract the audio track from a video as MP3, WAV or AAC.",
    categorySlug: "video",
    icon: "🎧",
    isFree: true,
    creditCost: 0,
    clientSide: true,
  },
  {
    slug: "video-to-mp3",
    name: "Video to MP3",
    shortDescription: "Convert MP4, MOV or WebM videos to MP3 audio files.",
    categorySlug: "video",
    icon: "🔊",
    isFeatured: true,
    isFree: true,
    creditCost: 0,
    clientSide: true,
  },
  // ── Writing (AI) ──
  {
    slug: "grammar-checker",
    name: "AI Grammar Checker",
    shortDescription: "Fix grammar, spelling and punctuation with AI — keeps your original voice.",
    categorySlug: "ai",
    icon: "✅",
    isFeatured: true,
    isFree: true,
    creditCost: 1,
    clientSide: false,
  },
  {
    slug: "paragraph-generator",
    name: "AI Paragraph Generator",
    shortDescription: "Turn a topic or a few keywords into a well-structured paragraph.",
    categorySlug: "ai",
    icon: "¶",
    isFree: true,
    creditCost: 1,
    clientSide: false,
  },
  {
    slug: "email-writer",
    name: "AI Email Writer",
    shortDescription: "Draft professional, casual or persuasive emails from a short brief.",
    categorySlug: "ai",
    icon: "✉️",
    isFeatured: true,
    isFree: true,
    creditCost: 1,
    clientSide: false,
  },
  {
    slug: "blog-title-generator",
    name: "Blog Title Generator",
    shortDescription: "Generate 10 catchy, SEO-friendly blog titles from a topic or keyword.",
    categorySlug: "ai",
    icon: "📝",
    isFree: true,
    creditCost: 1,
    clientSide: false,
  },
  {
    slug: "content-expander",
    name: "AI Content Expander",
    shortDescription: "Expand short notes or bullet points into full, detailed content.",
    categorySlug: "ai",
    icon: "📖",
    isFree: true,
    creditCost: 1,
    clientSide: false,
  },
  {
    slug: "tone-changer",
    name: "AI Tone Changer",
    shortDescription: "Rewrite any text in a different tone: friendly, formal, witty, empathetic.",
    categorySlug: "ai",
    icon: "🎭",
    isFree: true,
    creditCost: 1,
    clientSide: false,
  },
  // ── Converters ──
  {
    slug: "image-converter",
    name: "Image Format Converter",
    shortDescription: "Convert between PNG, JPG, WEBP and AVIF — client-side, no upload.",
    categorySlug: "converter",
    icon: "🖼️",
    isFeatured: true,
    isFree: true,
    creditCost: 0,
    clientSide: true,
  },
  {
    slug: "markdown-to-html",
    name: "Markdown ↔ HTML",
    shortDescription: "Convert Markdown to HTML or clean HTML back to Markdown.",
    categorySlug: "converter",
    icon: "M↓",
    isFree: true,
    creditCost: 0,
    clientSide: true,
  },
  {
    slug: "yaml-json",
    name: "YAML ↔ JSON",
    shortDescription: "Convert between YAML and JSON with proper formatting.",
    categorySlug: "converter",
    icon: "⇄",
    isFree: true,
    creditCost: 0,
    clientSide: true,
  },
  {
    slug: "xml-json",
    name: "XML ↔ JSON",
    shortDescription: "Convert XML to JSON or JSON back to XML instantly.",
    categorySlug: "converter",
    icon: "</>",
    isFree: true,
    creditCost: 0,
    clientSide: true,
  },
  {
    slug: "toml-json",
    name: "TOML ↔ JSON",
    shortDescription: "Convert between TOML config and JSON — great for Rust/Cargo files.",
    categorySlug: "converter",
    icon: "⇄",
    isFree: true,
    creditCost: 0,
    clientSide: true,
  },
  {
    slug: "excel-to-csv",
    name: "Excel to CSV",
    shortDescription: "Convert .xlsx or .xls spreadsheets to CSV files — pick any sheet.",
    categorySlug: "converter",
    icon: "📊",
    isFeatured: true,
    isFree: true,
    creditCost: 0,
    clientSide: true,
  },
];

export const getCategory = (slug: string) => CATEGORIES.find((c) => c.slug === slug);
export const getTool = (slug: string) => TOOLS.find((t) => t.slug === slug);
export const toolsInCategory = (slug: string) => TOOLS.filter((t) => t.categorySlug === slug);
export const featuredTools = () => TOOLS.filter((t) => t.isFeatured);