// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fdwpzixwvksjlicnovdo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZkd3B6aXh3dmtzamxpY25vdmRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQxODA1NDksImV4cCI6MjA5OTc1NjU0OX0.0MPmTzgHT5WtAAWFIJ88zTIpYnHmOSFJz4Lj1yaY9nE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});