import { useState, useMemo } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";
import { toast } from "sonner";

export default function HtaccessGeneratorTool() {
  const [forceHttps, setForceHttps] = useState(true);
  const [wwwMode, setWwwMode] = useState<"none" | "add" | "strip">("strip");
  const [notFound, setNotFound] = useState("/404.html");
  const [hotlink, setHotlink] = useState(false);
  const [hotlinkDomain, setHotlinkDomain] = useState("example.com");
  const [gzip, setGzip] = useState(true);
  const [cache, setCache] = useState(true);
  const [redirects, setRedirects] = useState("/old-page /new-page 301\n/blog/old /blog/new 301");

  const output = useMemo(() => {
    const b: string[] = [];
    b.push("# Generated by Nexatools htaccess-generator", "Options -Indexes", "");
    b.push("<IfModule mod_rewrite.c>", "RewriteEngine On");
    if (forceHttps) b.push("RewriteCond %{HTTPS} off", "RewriteRule ^(.*)$ https://%{HTTP_HOST}/$1 [R=301,L]");
    if (wwwMode === "strip") b.push("RewriteCond %{HTTP_HOST} ^www\\.(.+)$ [NC]", "RewriteRule ^(.*)$ https://%1/$1 [R=301,L]");
    if (wwwMode === "add") b.push("RewriteCond %{HTTP_HOST} !^www\\. [NC]", "RewriteRule ^(.*)$ https://www.%{HTTP_HOST}/$1 [R=301,L]");
    redirects.split("\n").map(l => l.trim()).filter(Boolean).forEach(l => {
      const [from, to, code = "301"] = l.split(/\s+/);
      if (from && to) b.push(`Redirect ${code} ${from} ${to}`);
    });
    if (hotlink) {
      b.push("RewriteCond %{HTTP_REFERER} !^$",
        `RewriteCond %{HTTP_REFERER} !^https?://(www\\.)?${hotlinkDomain.replace(/\./g, "\\.")}/.* [NC]`,
        "RewriteRule \\.(jpe?g|png|gif|webp|svg)$ - [F,NC]");
    }
    b.push("</IfModule>", "");
    if (notFound.trim()) b.push(`ErrorDocument 404 ${notFound.trim()}`, "");
    if (gzip) b.push("<IfModule mod_deflate.c>",
      "AddOutputFilterByType DEFLATE text/html text/plain text/xml text/css text/javascript application/javascript application/json application/xml image/svg+xml",
      "</IfModule>", "");
    if (cache) b.push("<IfModule mod_expires.c>", "ExpiresActive On",
      "ExpiresByType image/jpg \"access plus 1 year\"",
      "ExpiresByType image/jpeg \"access plus 1 year\"",
      "ExpiresByType image/png \"access plus 1 year\"",
      "ExpiresByType image/webp \"access plus 1 year\"",
      "ExpiresByType image/svg+xml \"access plus 1 year\"",
      "ExpiresByType text/css \"access plus 1 month\"",
      "ExpiresByType application/javascript \"access plus 1 month\"",
      "ExpiresByType text/html \"access plus 1 hour\"",
      "</IfModule>", "");
    b.push("<IfModule mod_headers.c>",
      "Header set X-Content-Type-Options \"nosniff\"",
      "Header set X-Frame-Options \"SAMEORIGIN\"",
      "Header set Referrer-Policy \"strict-origin-when-cross-origin\"",
      "</IfModule>");
    return b.join("\n") + "\n";
  }, [forceHttps, wwwMode, notFound, hotlink, hotlinkDomain, gzip, cache, redirects]);

  const download = () => {
    const blob = new Blob([output], { type: "text/plain" });
    const a = document.createElement("a"); a.href = URL.createObjectURL(blob); a.download = ".htaccess"; a.click();
  };

  return (
    <div className="space-y-4">
      <div className="grid gap-4 sm:grid-cols-2">
        <div className="rounded-md border p-4 space-y-3">
          <div className="flex items-center justify-between"><Label>Force HTTPS</Label><Switch checked={forceHttps} onCheckedChange={setForceHttps} /></div>
          <div>
            <Label>WWW handling</Label>
            <div className="mt-2 flex gap-2">
              {(["none","strip","add"] as const).map(m => (
                <Button key={m} type="button" size="sm" variant={wwwMode === m ? "default" : "outline"} onClick={() => setWwwMode(m)}>{m}</Button>
              ))}
            </div>
          </div>
          <div><Label>Custom 404 page</Label><Input className="mt-1" value={notFound} onChange={e => setNotFound(e.target.value)} /></div>
        </div>
        <div className="rounded-md border p-4 space-y-3">
          <div className="flex items-center justify-between"><Label>Gzip compression</Label><Switch checked={gzip} onCheckedChange={setGzip} /></div>
          <div className="flex items-center justify-between"><Label>Cache headers</Label><Switch checked={cache} onCheckedChange={setCache} /></div>
          <div className="flex items-center justify-between"><Label>Hotlink protection</Label><Switch checked={hotlink} onCheckedChange={setHotlink} /></div>
          {hotlink && <div><Label>Allowed domain</Label><Input className="mt-1" value={hotlinkDomain} onChange={e => setHotlinkDomain(e.target.value)} /></div>}
        </div>
      </div>
      <div>
        <Label>Redirects (one per line: <code className="text-xs">from to [code]</code>)</Label>
        <Textarea rows={4} className="mt-1 font-mono text-sm" value={redirects} onChange={(e) => setRedirects(e.target.value)} />
      </div>
      <div><Label>Output</Label><Textarea rows={14} className="mt-1 font-mono text-xs" value={output} readOnly /></div>
      <div className="flex gap-2">
        <Button onClick={() => { navigator.clipboard.writeText(output); toast.success("Copied"); }}>Copy</Button>
        <Button variant="outline" onClick={download}>Download .htaccess</Button>
      </div>
    </div>
  );
}