import { lazy, ComponentType, LazyExoticComponent } from "react";

export const TOOL_REGISTRY: Record<string, LazyExoticComponent<ComponentType>> = {
  "json-formatter": lazy(() => import("./json-formatter")),
  "base64": lazy(() => import("./base64")),
  "url-encoder": lazy(() => import("./url-encoder")),
  "jwt-decoder": lazy(() => import("./jwt-decoder")),
  "regex-tester": lazy(() => import("./regex-tester")),
  "password-generator": lazy(() => import("./password-generator")),
  "hash-generator": lazy(() => import("./hash-generator")),
  "color-converter": lazy(() => import("./color-converter")),
  "word-counter": lazy(() => import("./word-counter")),
  "case-converter": lazy(() => import("./case-converter")),
  "lorem-ipsum": lazy(() => import("./lorem-ipsum")),
  "text-to-speech": lazy(() => import("./text-to-speech")),
  "image-resizer": lazy(() => import("./image-resizer")),
  "image-compressor": lazy(() => import("./image-compressor")),
  "image-to-pdf": lazy(() => import("./image-to-pdf")),
  "pdf-merge": lazy(() => import("./pdf-merge")),
  "pdf-split": lazy(() => import("./pdf-split")),
  "pdf-compressor": lazy(() => import("./pdf-compressor")),
  "pdf-to-word": lazy(() => import("./pdf-to-word")),
  "ocr": lazy(() => import("./ocr")),
  "remove-background": lazy(() => import("./remove-background")),
  "summarize": lazy(() => import("./summarize")),
  "translate": lazy(() => import("./translate")),
  "rewrite": lazy(() => import("./rewrite")),
  "chat-pdf": lazy(() => import("./chat-pdf")),
  "csv-to-json": lazy(() => import("./csv-to-json")),
  "json-to-csv": lazy(() => import("./json-to-csv")),
  "uuid-generator": lazy(() => import("./uuid-generator")),
  "html-entities": lazy(() => import("./html-entities")),
  "timestamp-converter": lazy(() => import("./timestamp-converter")),
};