import { lazy, ComponentType, LazyExoticComponent } from "react";

// Skip building the registry (and its dynamic-import graph) during SSR so the
// Cloudflare Worker bundle doesn't ship pdfjs/pdf-lib/xlsx/docx/onnxruntime/
// imgly/tesseract/ffmpeg chunks it never executes — tool components are always
// rendered inside <ClientOnly> in src/routes/tools.$slug.tsx.
export const TOOL_REGISTRY: Record<string, LazyExoticComponent<ComponentType>> = import.meta.env.SSR ? {} : {
  "json-formatter": lazy(() => import("./json-formatter")),
  "base64": lazy(() => import("./base64")),
  "url-encoder": lazy(() => import("./url-encoder")),
  "jwt-decoder": lazy(() => import("./jwt-decoder")),
  "regex-tester": lazy(() => import("./regex-tester")),
  "password-generator": lazy(() => import("./password-generator")),
  "hash-generator": lazy(() => import("./hash-generator")),
  "color-converter": lazy(() => import("./color-converter")),
  "word-counter": lazy(() => import("./word-counter")),
  "case-converter": lazy(() => import("./case-converter")),
  "lorem-ipsum": lazy(() => import("./lorem-ipsum")),
  "text-to-speech": lazy(() => import("./text-to-speech")),
  "image-resizer": lazy(() => import("./image-resizer")),
  "image-compressor": lazy(() => import("./image-compressor")),
  "image-to-pdf": lazy(() => import("./image-to-pdf")),
  "pdf-merge": lazy(() => import("./pdf-merge")),
  "pdf-split": lazy(() => import("./pdf-split")),
  "pdf-compressor": lazy(() => import("./pdf-compressor")),
  "pdf-to-word": lazy(() => import("./pdf-to-word")),
  "ocr": lazy(() => import("./ocr")),
  "remove-background": lazy(() => import("./remove-background")),
  "summarize": lazy(() => import("./summarize")),
  "translate": lazy(() => import("./translate")),
  "rewrite": lazy(() => import("./rewrite")),
  "chat-pdf": lazy(() => import("./chat-pdf")),
  "csv-to-json": lazy(() => import("./csv-to-json")),
  "json-to-csv": lazy(() => import("./json-to-csv")),
  "uuid-generator": lazy(() => import("./uuid-generator")),
  "html-entities": lazy(() => import("./html-entities")),
  "timestamp-converter": lazy(() => import("./timestamp-converter")),
  "video-to-gif": lazy(() => import("./video-to-gif")),
  "video-trimmer": lazy(() => import("./video-trimmer")),
  "video-compressor": lazy(() => import("./video-compressor")),
  "audio-extractor": lazy(() => import("./audio-extractor")),
  "video-to-mp3": lazy(() => import("./video-to-mp3")),
  "grammar-checker": lazy(() => import("./grammar-checker")),
  "paragraph-generator": lazy(() => import("./paragraph-generator")),
  "email-writer": lazy(() => import("./email-writer")),
  "blog-title-generator": lazy(() => import("./blog-title-generator")),
  "content-expander": lazy(() => import("./content-expander")),
  "tone-changer": lazy(() => import("./tone-changer")),
  "image-converter": lazy(() => import("./image-converter")),
  "markdown-to-html": lazy(() => import("./markdown-to-html")),
  "yaml-json": lazy(() => import("./yaml-json")),
  "xml-json": lazy(() => import("./xml-json")),
  "toml-json": lazy(() => import("./toml-json")),
  "excel-to-csv": lazy(() => import("./excel-to-csv")),
  "image-crop": lazy(() => import("./image-crop")),
  "image-rotate-flip": lazy(() => import("./image-rotate-flip")),
  "image-remove-exif": lazy(() => import("./image-remove-exif")),
  "image-to-base64": lazy(() => import("./image-to-base64")),
  "pdf-rotate": lazy(() => import("./pdf-rotate")),
  "pdf-delete-pages": lazy(() => import("./pdf-delete-pages")),
  "pdf-to-images": lazy(() => import("./pdf-to-images")),
};